### ISSUE TITLE
Feature request: specify output file

### ISSUE THREAD

**Issue by apt1002** [rrthomas/nancy#1]
Currently Nancy writes its output to stdout. The user has to redirect the output to a file, something like:

    nancy --root $ROOT $TEMPLATE $PATH >$BUILD/$PATH/$TEMPLATE

When writing a lot of commands of this form, one per file of a large site, there is a danger of cut-and-paste errors, resulting in lost work and/or obscure bugs.

Please can you add a way to specify $BUILD, such that Nancy automatically writes the output to a file chosen as in the above example. I suggest an option "-o" or "--output" or something.

Preserve the existing behaviour (write to stdout) if the option is omitted or if "-" is specified.

It should be an error if $ROOT is a prefix of $BUILD or vice versa. I can't imagine that happenning on purpose, and anyway you can work around the restriction if you must.

For good error behaviour, output should perhaps be written to a temporary file and then atomically moved into place.

**Comment by apt1002** [comment]
On reflection, perhaps the output file should be $BUILD/$PATH, not $BUILD/$PATH/$TEMPLATE?

**Comment by rrthomas** [comment]
I'm sorry, I misread this request originally (before you filed the GitHub issue).

What I am quite happy to do is to add a `--output` flag to specify the output (as many programs do).

What I am not happy to do is to make rules about what the output should be called, or where it should go. For example, I currently write outputs into the input tree in some cases, and that seems fine to me.

Obviously, that doesn't really address the problem you are trying to fix, namely of repetition of bits of the path.

I will contact you privately about this, I have some ideas from the past that may help.
