### ISSUE TITLE
Remove dependency on RRT::Macro

### ISSUE THREAD

**Issue by apt1002** [rrthomas/nancy#2]
The dependency on RRT::Macro complicates installation, especially for non-Perl-programmers who don't know about PERL5LIB, and also for those who don't know how to use .bashrc .

RRT::Macro is only a dozen lines long, so I suggest inlining it into Nancy to remove the dependency.

**Comment by rrthomas** [comment]
Thanks, a good idea.

Maybe add RRT as a git submodule and then generate the nancy script by catting bits together?

I'll look into how `cloc` and/or `get-iplayer` do this.

**Comment by apt1002** [comment]
Arguably copy-and-paste is the right answer. I don't think it's particularly important that RRT::Macro and Nancy share the same code. Unless you expect to fix a lot of bugs in it, I suppose...
