### ISSUE TITLE
Feature request: $unpath

### ISSUE THREAD

**Issue by apt1002** [rrthomas/nancy#9]
A common use-case of Nancy is building HTML files that link to each other using relative URLs. It is difficult to get the relative URLs right. For example, suppose we have a file "template.html" which contains:

    $include{menu.html}

We generate two output files "index.html" and "some_dir/some_file.html":

    nancy template.html index --output build/index.html
    nancy template.html some_dir/some_file --output build/some_dir/some_file.html

Suppose "menu.html" includes a link:

    <a href="some_dir/some_file.html">

Then we have a problem. When the menu gets included in "index.html", the link works, but when the menu gets included in "some_dir/some_file.html" the link is broken.

A possible work-around is only to use absolute URLs. But that means I've lost flexibility in the URL where the site is hosted. In particular, I can't point my browser at "file://build", because none of the links begin with "/path/to/build/".

A better work-around is to place all output files in the same directory, i.e. to flatten the directory hierarchy inside "build". This is unsatisfactory because the correspondence of source to build files is confusing and a potential maintenance problem.

A better work-around is to make a file "path_to_root.txt" in every source directory, containing "." or ".." or "../.." as appropriate, and then to write the link as follows:

    <a href="$paste{path_to_root.txt}/some_dir/some_file.html">

However, it is annoying to have to do this in every link, and it is easy to forget to do so.

A better better work-around, using the same "path_to_root.txt" files, is to leave the links unchanged, but put the following in "template.html" (so that it appears in every HTML file):

    <base href="$paste{path_to_root.txt}">

However, this is still far from ideal. The "path_to_root.txt" files are confusing and distracting. When reorganising the directory tree, they become a maintenance problem.

Therefore, please introduce a Nancy command "$unpath" (or something) which expands to:

- "." if $PATH is empty.
- ".." if $PATH is depth 1.
- "../.." if $PATH is depth 2.
- "../../.." if $PATH is depth 3.
- Etc.

**Comment by rrthomas** [comment]
​You may want to look at how this used to be implemented (confusingly, also called `$root`). Sorry to make you reinvent the past.​ The most recent commit that had this was fd34ede9.

I removed it as part of making Nancy not web-specific; I'd rather not have such a feature in the core (unless perhaps it's useful for something else?).

**Comment by rrthomas** [comment]
(Also, before we had `$root`, we used fragments like your `path_to_root.txt`!)

**Comment by rrthomas** [comment]
As I said by email, @apt1002, you can use pipes in Nancy commands, so you could implement `$unpath` by:

    $paste{sh,-c,echo $path | sed s:[^/]*:\.\.:g}

though I guess for regular use you'd want to put that in a script.

**Comment by apt1002** [comment]
A small correction for those tempted to use the above "sed" trick: if your build directory is laid out like mine, then you have to use "dirname" to remove one level from the path, and you have to make sure "." does not become "..". My <base> tag looks like this:

    <base href="$paste{sh,-c,dirname $path | sed s:[^./][^/]*:\.\.:g}">

**Comment by rrthomas** [comment]
Take a look at 6.0rc5, which implements recursive `$include`. This does not of itself provide `$unpath`, but does mean that without programming you can simply have a `path_to_root.txt` file containing `..` in every directory. It also solves the breadcrumb example (and I use it for that).

**Comment by apt1002** [comment]
Yes, I like that.
